### PR TITLE
Updated repository.yaml

### PR DESCRIPTION
**Pull request by miman**
Added the following plugins:
Forge project plugin
JAXB plugin
Drools plugin

### CODE REVIEW

**Comment by gastaldi** [comment]
Hi @miman,

This looks awesome, but I wonder how different is the forge-prj plugin from the built-in "new-project" and "plugins setup" ?

**Comment by miman** [comment]
Hello Gastaldi,

Actually not much, I hadn't found that plugin (now I know better ;-)
Major difference is that I have < dependencies-as-resource-root/ > added to my forge.xml, while I always have a dependency to a util project and that I automatically create & bind a Facet to the plugin.

But as there already is an existing plugin for this I will remove my plugin from my checkin.

**Comment by gastaldi** [comment]
Perhaps we could include this feature of adding dependencies as resource root  in our built-in plugin. Could you please open a JIRA and if possible submit a pull-request allowing this? 

Best Regards,
George Gastaldi

**Comment by miman** [comment]
Yes, I will see if I can add this functionality to the existing plugin code & do a pull request on that change.

Do you want me to send a new request for the other 2 plugins I have in this request or should I leave them in this pull request ?

**Comment by gastaldi** [comment]
You may push again to your repository and the pull request will be
automatically updated. Be sure also to update to the latest version in the
master branch

Em domingo, 11 de agosto de 2013, Mikael Thorman escreveu:

**Comment by gastaldi** [comment]
Also try to rebase to a single commit, if possible

Em domingo, 11 de agosto de 2013, George Gastaldi escreveu:

**Comment by gastaldi** [comment]
Closing it as Forge 1.x is no longer active

**Pull request closed without merging**
