### PR TITLE
added openshihift repo

### PR DESCRIPTION
**Pull request by bdecoste**

### CODE REVIEW

**Comment by lincolnthree** [comment]
Did you want to remove the old plugins as well?

**Comment by bdecoste** [comment]
I think we should leave the express repo for now since it's still valid/functional. I don't see a problem removing the flex one since it's dead

**Comment by lincolnthree** [comment]
Isn't "openshift" the same as "openshift-express"? And yes. Could you remove the Flex repo in your fork (It should automatically update the pull request?)

**Comment by bdecoste** [comment]
Yes, I just don't want to get rid of express and break anything until we have some doc

**Pull request merged**
