### PR TITLE
added Boottheme Plugin

### PR DESCRIPTION
**Pull request by lefloh**
Helps building your own Bootstrap Theme

### CODE REVIEW

**Comment by gastaldi** [comment]
Amazing ! Thank you !

**Comment by lefloh** [comment]
Seems like I've forgotten the '.git' in the gitrepo line :/
Sorry, George. Can we reopen this PullRequest? Or shall I pull again?

**Comment by gastaldi** [comment]
Ah, np, I can fix it for you. Just a sec

**Comment by gastaldi** [comment]
Done. Thanks once again !

**Comment by lincolnthree** [comment]
Isn't he the best? he's the best.

On Fri, May 10, 2013 at 11:14 AM, George Gastaldi
notifications@github.comwrote:

> Ah, np, I can fix it for you. Just a sec
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/forge/plugin-repository/pull/29#issuecomment-17726019
> .

## 

Lincoln Baxter, III
http://ocpsoft.org
"Simpler is better."

**Comment by lefloh** [comment]
he is :) thanks a million!

**Pull request merged**
